services:
    web:
        build:
            context: .
        container_name: "news_web"
        restart: always
        command:
            -   bash ./entrypoint.sh
        volumes:
            - ./static:/usr/src/app/static
        ports:
            - 8080:8080
        env_file:
            - .env.dev
        networks:
            - my_network
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: "news_db"
        restart: always
        environment:
            POSTGRES_DB: news_api_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
        volumes:
            -   db_data:/var/lib/postgresql/data
        networks:
            - my_network

networks:
    my_network:

volumes:
    db_data: